### PR TITLE
Updated path to be platform-independent

### PR DESCRIPTION
**Pull request by giacomo-b**
Updated `path` so that it is platform independent:

**Before**:
`path = directory + self.filename + ".json"`

**After**:
`path = os.path.join(directory, self.filename + ".json")`

### CODE REVIEW

**Comment by alexal1** [comment]
Oh thanks. Wait but there are a lot of such places in the code. So they are completely broken on windows, aren't they?

**Comment by giacomo-b** [comment]
Sorry, I just noticed it's in other places as well. I will try and go through them asap.
It _should_ be working on Windows too, this just ensured it [works everywhere](https://stackoverflow.com/a/6036156/5617293).

**Comment by giacomo-b** [comment]
I went through all the files, there shouldn't be any path left to fix.

**Comment by alexal1** [comment]
Great job, just added to the next release 👍

**Pull request closed without merging**
