### PR TITLE
Fix search content description case

### PR DESCRIPTION
**Pull request by arthurspa**
Instagram app has updated the search content
description text case from 'Search and Explore'
to 'Search and explore'. This is causing the bot to
brash.

### CODE REVIEW

**Comment by arthurspa** [comment]
This commit fixes #113

**Comment by gvmturl** [comment]
Hey @arthurspa provided solution does not solve #113

**Comment by arthurspa** [comment]
Hi @gvmturl , how not? I check the logs in #113 , it's exactly the same problem I was having when I cloned the repo yesterday.
I only managed to run the bot when I fixed the case as in my commit. If I remove this fix it stops working, at least for me.

In his logs:

```
Traceback (most recent call last):
  File "insomniac.py", line 385, in wrapper
    func(*args, **kwargs)
  File "insomniac.py", line 193, in job
    on_interaction)
  File "C:\Users\filip\Insomniac\src\action_handle_blogger.py", line 33, in handle_blogger
    if not _open_user_followers(device, username):
  File "C:\Users\filip\Insomniac\src\action_handle_blogger.py", line 47, in _open_user_followers
    navigate(device, Tabs.SEARCH)
  File "C:\Users\filip\Insomniac\src\navigation.py", line 14, in navigate
    _navigate_to_search(device)
  File "C:\Users\filip\Insomniac\src\navigation.py", line 96, in _navigate_to_search
    search_in_action_bar.click()
  File "C:\Users\filip\Insomniac\src\device_facade.py", line 144, in click
    raise DeviceFacade.JsonRpcError(e)
src.device_facade.DeviceFacade.JsonRpcError: -32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 64, 'childOrSibling': [], 'childOrSiblingSelector': [], 'description': 'Search and Explore'}], 
```

**Comment by randinfo** [comment]
```
[09/24 20:45:39] Traceback (most recent call last):
  File "/Users/amar/Documents/dev/insomniac/src/device_facade.py", line 142, in click
    self.viewV2.click(UI_TIMEOUT_LONG)
  File "/Users/amar/anaconda3/lib/python3.7/site-packages/uiautomator2/_selector.py", line 150, in click
    self.must_wait(timeout=timeout)
  File "/Users/amar/anaconda3/lib/python3.7/site-packages/uiautomator2/_selector.py", line 345, in must_wait
    raise UiObjectNotFoundError({'code': -32002, 'data': str(self.selector), 'method': 'wait'})
uiautomator2.exceptions.UiObjectNotFoundError: -32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 256, 'childOrSibling': [], 'childOrSiblingSelector': [], 'descriptionMatches': '[Ss]earch and [Ee]xplore'}], resourceId='com.instagram.android:id/action_bar', className='android.widget.LinearLayout'], method: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 385, in wrapper
    func(*args, **kwargs)
  File "insomniac.py", line 193, in job
    on_interaction)
  File "/Users/amar/Documents/dev/insomniac/src/action_handle_blogger.py", line 33, in handle_blogger
    if not _open_user_followers(device, username):
  File "/Users/amar/Documents/dev/insomniac/src/action_handle_blogger.py", line 47, in _open_user_followers
    navigate(device, Tabs.SEARCH)
  File "/Users/amar/Documents/dev/insomniac/src/navigation.py", line 14, in navigate
    _navigate_to_search(device)
  File "/Users/amar/Documents/dev/insomniac/src/navigation.py", line 96, in _navigate_to_search
    search_in_action_bar.click()
  File "/Users/amar/Documents/dev/insomniac/src/device_facade.py", line 144, in click
    raise DeviceFacade.JsonRpcError(e)
src.device_facade.DeviceFacade.JsonRpcError: -32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 256, 'childOrSibling': [], 'childOrSiblingSelector': [], 'descriptionMatches': '[Ss]earch and [Ee]xplore'}], resourceId='com.instagram.android:id/action_bar', className='android.widget.LinearLayout'], method: None

```

**Comment by alexal1** [comment]
@arthurspa works like a charm, thank you!

**Comment by randinfo** [comment]
are you sure mate ? i used right now with these modifications and i still get the error

**Comment by alexal1** [comment]
@randinfo please try it on `v2.1.7`

**Pull request merged**
